[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Netlify Functions 环境变量
[functions.environment]
  SUPABASE_URL = "https://dsrzlugtzanbzwzagakd.supabase.co"
  SUPABASE_ANON_KEY = "sb_publishable_vhPfTkE2AhtBbSqKo6goFQ_vK518sVh%"

# 重定向和自定义头信息
[context.production.environment]
  HUGO_ENV = "production"

# 设置Netlify博客集成（可选）
[context.deploy-preview]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"

# 配置头信息，提高安全性和性能
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 为404页面设置自定义状态码
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
